### ISSUE TITLE
Question about manual approvals

### ISSUE THREAD

**Issue by polothy** [NetaNir/meerkats#19]
Hello!

Sorry about this unsolicited feedback, but I was curious if the proposed API would be able to support the following use case:

1. _All the pipeline actions leading up to this point_
2. For each region in production, generate a CloudFormation change set.
3. Hit the manually approve button to deploy to production.
4. For each region in production, apply the change set.

Looking at #15, the example stacks and proposed API, this is all looking _really_ amazing.  The CDK is really doing the heavy lifting to deploy an application to anywhere we want 💯 

Cheers and thanks for working on this!

**Comment by rix0rrr** [comment]
We might be able to do that. Your interest seems to be in deploying all production stages in parallel?

This works as long as there aren't multiple stacks in your application. As soon as there are stacks A and B (that depend on each other), we have to do a 2-step approval process:

* Prepare all A changes
* Manual approval
* Execute all A changes
* Prepare all B changes
* Manual approval
* Execute all B changes

Does that work for you?

**Comment by polothy** [comment]
Hey, thanks for the response!

> We might be able to do that. Your interest seems to be in deploying all production stages in parallel?

Sorry, my question was vague.  In the proposed API, I wasn't sure if you could insert a single manual approve between the creation of the change sets across regions and the deployment of those change sets across regions.  From your response, it looks like it is or at least would be possible and that's awesome!

> This works as long as there aren't multiple stacks in your application.

I don't think we have a use case for multiple stacks just yet... but I have a feeling we could live with multiple approvals.  I think the real problem would be if we couldn't insert any manual approvals.

Thanks again for writing back, I really appreciate it!  Really enjoying the CDK, a very unique and productive way to write infrastructure.
